server:
  port: 8080  # El puerto único para el Frontend

jwt:
  secret: WriteHereYourSecretStringForTokenSigningCredentials

gateway:
  public-paths:
    - /api/v1/plans
    - /api/v1/users/signup
    - /api/v1/users/signin
    - /api/v1/users/available-roles
    - /v3/api-docs
    - /swagger-ui
    - /swagger-ui.html
    - /swagger-resources
    - /webjars
    - /error
    - /actuator

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5434/yaku_iam
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    gateway:
      routes:

        # Rutas hacia el microservicio de Equipment
        - id: equipment-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/farms/**, /api/v1/ponds/**, /api/v1/equipment/**

        # Rutas hacia el microservicio de Notification
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/users/*/notifications, /api/v1/users/*/notifications/**, /api/v1/users/*/device-tokens, /api/v1/users/*/device-tokens/**, /api/v1/webhooks/notifications, /api/v1/webhooks/notifications/**

        # Rutas hacia el microservicio de Subscription
        - id: subscription-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/subscriptions/**, /api/v1/plans/**, /api/v1/payments/**, /api/v1/webhooks/stripe/**

        # Rutas hacia el microservicio de Telemetry
        - id: telemetry-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/telemetry/**
authorization:
  jwt:
    secret: WriteHereYourSecretStringForTokenSigningCredentials
    expiration:
      days: 7
documentation:
  application:
    description: Yaku API Gateway
    version: 1.0.0